"""Add file attachment support to project chats

Revision ID: 3583e047f50d
Revises: 
Create Date: 2025-06-08 22:52:56.342787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3583e047f50d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_chats', schema=None) as batch_op:
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_name')
        batch_op.drop_column('file_path')
        batch_op.drop_column('message_type')

    # ### end Alembic commands ###
